### ISSUE TITLE
Store negative/inverted types in type propagator nodes

### ISSUE THREAD

**Issue by Fidget-Spinner** [pylbbv/pylbbv#4]
# Feature or enhancement

Type propagator nodes should be able to store that it's *not* a certain type, eg. `!int` or `!float`.

# Pitch

This will:
- simplify the type prop state
- prevent duplicate failed type checks, e.g. if we know something is `!int`, we don't need to check it's an `int` again. The current lbbv paper which uses only positive type success information can't do this.

**Comment by Fidget-Spinner** [comment]
Actually, we don't need 128 bits for this. I realised we can just manually the first 32 bits to represent types, then the next 32 can be used to indicate the negative types. So 64 bits is enough for TYPE_ROOT. Note that we can't use enums becauses enums in C are not guaranteed to fit into 32-bits.

E.g.
```C
#define PYLONG 1
#define PYFLOAT 2
#define PYRAWFLOAT 3
...

PyTypeObject *
int_to_type(int x)
{
switch(x) {
    case PYLONG:
        return PyLong_Type
...
}
}
```

**Comment by JuliaPoo** [comment]
Wait why not a bitmask in case simply (!x || x) is not expressive enough? The bitmask representation would allow for ~60 types which should be sufficient for now.

If we're gonna do "inverted types" we can use ~59 bits for $2^{59}$ types and 1 bit for "inverted or not"

**Comment by Fidget-Spinner** [comment]
Yeah bitmask is fine too. In fact it might be better because we can then do

```C
#define PYLONG 1 << 0
#define PYFLOAT 1 << 1
#define PYRAWFLOAT 1 << 2

switch(type1_bitmask | type2_bitmask >> 32)
    case (PYLONG | PYLONG >> 32):
    ....
```
which is definitely a jump table.

**Comment by Fidget-Spinner** [comment]
Summary from our discussion:

Change the type root to a 
```
|-----31-bits singular positive type tag ----|------31-bits negative bitmask-----|---2-bit tag---|
```
We need a singular positive type tag because the type prop and lbbv gains positive information and tests for a certain type.

The bitmask indicates what types it is NOT (failed type checks).

2-bit tag for pointer tagging.

Note that for comparison of type roots (either during backwards jumping or other areas). We **only** compare the positive type tag and NOT the negative bitmask. ie. negative type unions will not affect the distinctness of a type. So two type roots with thes same positive types but different negative bitmask are considered equivalent. This is to prevent "flip-flopping" of code due to different guard failures and thus different negative bitmask.

**Comment by JuliaPoo** [comment]
I'm thinking we don't need a 31-bits positive type tag, since we only have one possible positive type, I propose the following layout for a type root:
```
|------62-bits negative bitmask/tagged pointer-----|-------2-bit tag-------|
                                                   |--is_pos--|--node_type-|
```
I can reduce the `node_type` to only use 1 bit. Since we can't have negative types and a positive type at the same time, the saved 1-bit can be used to store if the type is a positive type (if so then the 62-bits is interpreted as per current format), otherwise the remaining bits serves as the negative bitmask.

As for unknown type, it will be interpreted as a positive type with null pointer as per current format.

This will allow supporting up to 62 types, and also simplifies implementation.

The downside is that currently the 2-bit `node_type` can detect nodes with invalid `node_type` tags (the `0` tag), but IMO such a bug only occurs early in the development of the type prop case generator.

Note that now there is two types of null:
1. Null with positive tag with zero-ed 62-bits: Every node starts as this, we don't know what type it is at all
2. Null with negative tag with one-ed 62-bits: We have tried every check but still don't know what type it is.

**Comment by Fidget-Spinner** [comment]
Follow-up:

The reason why the new approach works is because once we get a positive type, it obsoletes all the negative type information (e.g. if we know something is `str`, then even if we know `!int`, `!float` that's useless). So it's okay to wipe the negative type information.

**Comment by JuliaPoo** [comment]
As discussed in #26, we are deciding to retain the 2-bit `node_type` tag because `TYPE_NULL` is immensely useful at detecting a raw pointer that somehow made it into the type context. The new format is
```
|------62-bits negative bitmask/tagged pointer-----|-------2-bit tag-------|
                                                   |---is_pos + node_type--|
```

If the tag is:
- 0 -> `TYPE_NULL`
- 1 -> `TYPE_ROOT_POSITIVE`, a type root with a positive type (tagged pointer to a `PyTypeObject`)
- 2 -> `TYPE_REF`, a type reference
- 3 -> `TYPE_ROOT_NEGATIVE`, a type root with a negative type bitmask

Note that this distinguishes two kinds of NULL:
- `POSITIVE_NULL`: Every node starts with this `NULL`
- `NEGATIVE_NULL`: We have attempted every guard on this and none passes.

This will be the format of a type node I'll be pursuing.
